apiversion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata: 
  name: eksdono
  region: us-east-1

nodegroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 1
    volumesize: 80
  availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]